beurs/urls.py
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from api.account.viewsets import UserViewSet, CustomerViewSet
from django.views.generic import TemplateView

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'customers',CustomerViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    # social-auth-app-django (github,google,authO)
    # only for authO =  python-jose no need for urls/settings
    path('',include('social_django.urls')),
]
urlpatterns += i18n_patterns(
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('users/', include('users.urls')),
    path('posts/',include('posts.urls')),
)
# (temp) path for browser api view
urlpatterns += [
    path('api-auth/', include('rest_framework.urls'))
]
# djoser path
urlpatterns += [
    path('auth/', include('djoser.urls.authtoken')),
    path('auth/', include('djoser.urls')),
    # jwt auth
    path('auth/', include('djoser.urls.jwt')),
]

# other api paths
urlpatterns +=[
    path('api/v1/', include(router.urls)),
]


# djoser urls
# ************************************
# step N 1: register user

# url: auth/users/
# other features
# url: auth/users/...кучи разных экстра для создания и опереций над юзерами
# smth like: confirm email, reset psw
# step N2
# activate
# auth/users/activate
# http://127.0.0.1:8080/activate/NDM/5ir-d995..


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import (PostFormListView,
                    PostDelete,
                    PostHide,
                    ReportListView,
                    ReportPost,
                    BlockUser,
                    )

app_name = 'posts'

urlpatterns = [
    path('',PostFormListView.as_view(),name="post-form"),
    path('delete-post/<int:pk>/',PostDelete.as_view(),name="post-delete"),
    path('hide-post/<int:pk>/',PostHide.as_view(),name="post-hide"),
    path('reports/',ReportListView.as_view(),name="report-list"),
    path('report-post/<int:pk>/',ReportPost.as_view(),name="report-post"),
    path('block-user/<int:pk>/',BlockUser.as_view(),name="ban-user"),
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=255, default="")
    count = models.SmallIntegerField(default=0)
    hidden = models.BooleanField(default=False)
    date_hidden = models.DateTimeField(null=True, blank=True)
    deleted_by = models.ForeignKey(User,
                                   on_delete=models.DO_NOTHING,
                                   blank=True,
                                   null=True,
                                   related_name="moderator")

    def __str__(self):
        return f'Written by {self.user}'

    class Meta:
        permissions = (('can_mark_inappropriate', 'can mark as inappropr'),)


class Report(models.Model):
    reported_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f"done by:{self.reported_by} on post {self.post.id}"

posts/forms.py
from django.forms import ModelForm, TextInput

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['content']
        widgets = {
            'content': TextInput(attrs={'class': 'input', 'placeholder': 'say smth'})
        }

posts/views.py
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import (CreateView,
                                  DeleteView,
                                  ListView,
                                  RedirectView,
                                  View
                                  )
from django.contrib.auth.mixins import PermissionRequiredMixin as PRM
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
# from django.contrib import messages
from .models import Post, Report
from .forms import PostForm
from django.urls import reverse_lazy
from django.utils import timezone
from django.contrib.auth import get_user_model


class PostFormListView(CreateView):
    form_class = PostForm
    template_name = "posts/post_form.html"
    success_url = reverse_lazy('posts:post-form')

    def get_queryset(self):
        return Post.objects.filter(hidden=False).order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = self.get_queryset()
        return context

    def form_valid(self, form):
        post = form.save(commit=False)
        post.user = self.request.user
        post.save()
        return super().form_valid(form)


class PostDelete(LRM,DeleteView):
    """only user who wrote a post can delete it"""
    model = Post
    success_url = reverse_lazy('posts:post-form')

    def get_queryset(self):
        return Post.objects.filter(user=self.request.user)


class ReportListView(LRM,PRM, ListView):
    """in report view not a list of reports but list of posts with attr times_reported
    where total count report saved"""
    permission_required = ['posts.view_report']
    context_object_name = 'reports'
    template_name = 'posts/report_list.html'

    def get_queryset(self):
        return Post.objects.annotate(times_reported=Count('report')).filter(times_reported__gt=0).all()


class ReportPost(LRM,RedirectView):
    http_method_names = ("post",)

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy("posts:post-form")

    def post(self, request, *args, **kwargs):
        """report post avoiding dubble reporting
        method .get_or_create provides the uniqueness of reported_user"""
        post_pk = kwargs.get("pk")
        print("post_id", post_pk)
        post = get_object_or_404(Post, pk=post_pk)

        report, created = Report.objects.get_or_create(
            post=post,
            reported_by=request.user
        )
        report.save()
        return super().post(request, *args, **kwargs)


class PostHide(LRM,PRM, RedirectView):
    permission_required = ('posts.change_post',)

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy("posts:report-list")

    def post(self, request, *args, **kwargs):
        post_to_hide = get_object_or_404(Post, id=self.kwargs.get('pk'))
        if not post_to_hide.hidden:
            post_to_hide.hidden = True
        post_to_hide.date_hidden = timezone.now()
        post_to_hide.deleted_by = request.user
        post_to_hide.save()
        return super().post(request, *args, **kwargs)


class BlockUser(LRM,PRM, RedirectView):
    permission_required = ('users.change_user',)

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy("posts:report-list")

    def post(self, request, *args, **kwargs):
        print("user id from kwargs:", kwargs.get('pk'))
        User = get_user_model()
        user = get_object_or_404(User, id=kwargs.get('pk'))
        print("user to ban", user, user.is_active)

        for post in user.posts.all():
            if not post.hidden:
                post.hidden = True
                post.date_hidden = timezone.now()
                post.deleted_by = request.user
                post.save()
        user.is_active = False
        user.save()
        return super().post(request, *args, **kwargs)

templates/posts/post_form.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{%block content %}
{% if user.is_authenticated %}
<div class="mt-3 container">
    <form action="{% url 'posts:post-form' %}" method="post">
        <article class="media">
            <div class="media-content">
                <div class="field">
                    <p class="control">
                        {% csrf_token %}
                    <div class="field has-addons">
                        <div class="control is-expanded">
                            {{form.content}}
                        </div>
                        <div class="control">
                            <button type="submit" class='btn btn-success'>Create New Post</button>
                        </div>
                    </div>
                    </p>
                </div>
            </div>
        </article>
    </form>

</div>
{% endif %}
<div class="mt-3 container">
    {% if posts %}
    {% for post in posts%}
    <div class="mt-3 d-flex justify-content-between">
        <div class="visible-border">Author:{{post.user}}</div>
        <div>Written: {{post.created_at|naturaltime}}</div>
        <div>
            {% if perms.posts.can_mark_inappropriate %}
            <span class="badge badge-success">Mark strange content</span>
            {% endif %}
        </div>
        {% if post.user != request.user %}
        {% include 'posts/_forms/report_form.html' %}
        {% elif post.user == request.user %}
        {% include 'posts/_forms/post_confirm_delete.html' %}
        {% endif %}
    </div>
    <div class="visible-border">{{post.content}}</div>
    {% endfor %}
    {%else %}
    <p>No content yet</p>
    {% endif %}
</div>
{% endblock %}

templates/posts/report_list.html
{% extends 'base.html' %}
{% load static %}
<!--TODO: remove table and add just div's-->
{%block content %}
<div class="mt-3 container">
    {% if reports %}
    {% for report in reports%}
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Post Id</th>
            <th scope="col">Post Author</th>
            <th scope="col">Status Author</th>
            <th scope="col">Times reported</th>
            <th scope="col">Reported by(#Id)</th>
            <th scope="col">Block Post </th>
            <th scope="col">Post hidden(time)</th>
<!--            <th scope="col">Block Author</th>-->

        </tr>
        </thead>
        <tbody>
        {% for post in reports %}
        <tr>
            <th scope="row">{{post.id}}</th>
            <td>{{post.user}}</td>

            <td>
                {% if post.user.is_active %}
                  {% include 'posts/_forms/block_user_button.html' %}
                {% else %}
                User is banned
                {% endif %}
            </td>
            <td>{{post.times_reported}}</td>
            <td>
            {% for report in post.report_set.all%}
               <p>{{report.reported_by}} (#{{report.reported_by.id}})</p>
            {% endfor %}
            </td>
            <td>
                {% if not post.hidden %}
                    {% include 'posts/_forms/hide_post_button.html' %}
                {%else %}
                    <p>Hidden by {{user}}</p>
                {% endif %}
            </td>
            <td>
                {% if post.date_hidden%}
                <p>{{post.date_hidden}}</p>
                {% endif %}
            </td>


        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endfor %}
    {%else %}
    <p>No reports</p>
    {% endif %}
</div>
{% endblock %}