beurs/urls.py
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from api.account.viewsets import UserViewSet, CustomerViewSet
from django.views.generic import TemplateView

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'customers',CustomerViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    # social-auth-app-django (github,google,authO)
    # only for authO =  python-jose no need for urls/settings
    path('',include('social_django.urls')),
]
urlpatterns += i18n_patterns(
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('users/', include('users.urls')),
    path('posts/',include('posts.urls')),
)
# (temp) path for browser api view
urlpatterns += [
    path('api-auth/', include('rest_framework.urls'))
]
# djoser path
urlpatterns += [
    path('auth/', include('djoser.urls.authtoken')),
    path('auth/', include('djoser.urls')),
    # jwt auth
    path('auth/', include('djoser.urls.jwt')),
]

# other api paths
urlpatterns +=[
    path('api/v1/', include(router.urls)),
]


# djoser urls
# ************************************
# step N 1: register user

# url: auth/users/
# other features
# url: auth/users/...кучи разных экстра для создания и опереций над юзерами
# smth like: confirm email, reset psw
# step N2
# activate
# auth/users/activate
# http://127.0.0.1:8080/activate/NDM/5ir-d995..


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import (CustomerRegister,
                    CustomerDashboard,
                    EmployeeRegister,
                    EmployeeDashboard,
                    logout
                    )

app_name = 'users'

urlpatterns = [
    path('customer-registration/', CustomerRegister.as_view(),name='customer-signup'),
    path('customer-dashboard/', CustomerDashboard.as_view(),name='customer-dashboard'),
    path('employee-registration/', EmployeeRegister.as_view(),name='employee-signup'),
    path('employee-dashboard/', EmployeeDashboard.as_view(),name='employee-dashboard'),
    path('logout/',logout,name='logout')
    
]

users/models.py
#  https://djangotricks.blogspot.com/search/label/Django%20REST%20Framework (about upload drf)
import os
import sys
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import PermissionsMixin
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from .managers import CustomUserManager
from .utils import upload_to
import uuid
from django.utils import timezone


class User(AbstractUser):
    """ 
    username + email for signup; email for login;
    user should choose at the moment of signUp one of two options: 
    is_customer or is employee;
    admin/staff members could keep default values;
    """
    username = models.CharField(_("Username"), unique=True, max_length=120)
    email = models.EmailField(_("Email"), unique=True)
    avatar = models.ImageField(_("Avatar"), upload_to=upload_to, blank=True)
    is_customer = models.BooleanField(_("customer status"), default=False)
    is_employee = models.BooleanField(_("employee status"), default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    def __str__(self):
        return self.username


class CommonInfo(models.Model):
    # created_at = models.DateTimeField(auto_now_add=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        abstract = True
        ordering = ('-created_at',)


class Customer(CommonInfo):
    """ extra attr unid to display in public space"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    unid = models.UUIDField(max_length=255, default=uuid.uuid4, editable=False)
    designation = models.CharField(help_text=_("Company Name"), max_length=120, default="")
    location = models.CharField(help_text=_("Company Name"), max_length=250, default="")
    phone_number = models.CharField(help_text=_("Your Phone"), max_length=20, default="")
    add_phone_number = models.CharField(help_text=_("Extra Phone"), max_length=20, default="")

    class Meta(CommonInfo.Meta):
        pass

    def __str__(self):
        return f'Customer {self.user.username}'


class Employee(CommonInfo):
    """ extra attr unid to display in public space"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    unid = models.UUIDField(max_length=255, default=uuid.uuid4, editable=False)
    designation = models.CharField(help_text=_("Company Name"), max_length=120, default="")
    location = models.CharField(help_text=_("Location"), max_length=250, default="")
    phone_number = models.CharField(help_text=_("Your Phone"), max_length=20, default="")
    add_phone_number = models.CharField(help_text=_("Extra Phone"), max_length=20, default="")

    class Meta(CommonInfo.Meta):
        pass

    def __str__(self):
        return f"Employee {self.user.username}"

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.db import transaction
from .models import Customer,Employee

User = get_user_model()

# class PersonForm(forms.ModelForm):
#     class Meta:
#        fields = ('location','phone_number','add_form_number')  

# class CustomerForm(PersonForm):
class CustomerForm(forms.ModelForm):
    location = forms.CharField(max_length=5)
    phone_number = forms.CharField(widget = forms.NumberInput)
    add_phone_number = forms.CharField(widget = forms.NumberInput,required=False)

    class Meta:
        model = Customer
        fields = ('designation','location','phone_number','add_phone_number')  
        

# class EmployeeForm(PersonForm):
class EmployeeForm(forms.ModelForm):
    phone_number = forms.CharField(widget = forms.NumberInput)
    add_phone_number = forms.CharField(widget = forms.NumberInput)

    class Meta:
        model = Employee
        fields = ('location','phone_number','add_phone_number')  
          

     

        
    

templates/customer/customer-dashboard.html
{% extends 'base.html' %}
{% load static i18n %} 

{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col col-md-10">
            <h1 class="text-center">{% trans 'Customer dashboard' %}</h1>
        </div>
    </div>
    
</div>

{% endblock content %}

templates/customer/customer-form.html
{% extends 'base.html' %}
{% load static i18n %} 
{% load widget_tweaks %}

{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col col-md-10">
            <h1 class="text-center">Customer form </h1>            
            <form id="cust-signup" class="my-form" action="{% url 'users:customer-signup' %}" method="POST" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_designation">Designation:</label>
                    <input type="text" name="designation" maxlength="120" class="form-control" required="" id="id_designation"></div>
                    <p class="attention" id="designation-errors"></p>

                <div class="form-group">
                    <label for="id_location">Location:</label>
                    <input type="text" name="location" maxlength="5" class="form-control" required="" id="id_location"></div>   
                <p class="attention" id="location-errors"></p>                                                
                <div class="form-group">
                    <label for="id_phone_number">Phone number:</label>
                    <input type="number" name="phone_number" class="form-control" required="" id="id_phone_number"></div>
                    <p class="attention" id="phone-errors"></p>                                              
                <div class="form-group">
                    <label for="id_add_phone_number">Add phone number:</label>
                    <input type="number" name="add_phone_number" class="form-control" required="" id="id_add_phone_number"></div>
                    <p class="attention" id="add-phone-errors"></p>                                              
                    <div class="but-center mt-2">  
                        <input type="submit" value="Register as customer" class="btn  btn-primary but-decor">
                    </div>
                      
                  </form>
                  <div id="all-errors"></div>                                                
                
                </div>
            </div>    
        </div>
        {% endblock content %}
        
        {% block js %}
        <script>   
            
            // const msgNonFields = $('.alert-msg-non-fields'); 
            $("#cust-signup").on('submit',function(e){
             e.preventDefault();
             const url = $(this).attr('action'); 
             const data = $(this).serialize(); 
                           
             $.ajax({
                url,
                data:data,
                method:'POST',
                success:function(response){
                    console.log("resp to redirect",response.redirect_to);
                    window.location = response.redirect_to;
                    //window.location = '/users/customer-dashboard';

                },
                error:function(err){
                    const generalErr = ("#all-errors")
                    const design = $("#designation-errors");    
                    const location = $('#location-errors');
                    const phone = $("#phone-errors");    
                    const addPhone = $('#add-phone-errors');
                        
                   if(err.status===500){
                    console.log("error 500",err.status);  
                    generalErr.html('<p>Something went wrong on the server</p>') 
                   }else if(err.status ===400){
                   // from backend str = err
                   let source = JSON.parse(err.responseJSON.errors);
                   design.html(source['designation'][0].message);
                   location.html(source['location'][0].message);
                   phone.html(source['phone_number'][0].message);
                   addPhone.html(source['add_phone_number'][0].message)
                                
                   
                   }else{
                    console.log("smth went wrong; status:",err.status); 
                   }                   
                }
            });
        })            
    </script> 
{% endblock %}
               
                
                
                      