beurs/urls.py
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from api.account.viewsets import UserViewSet, CustomerViewSet
from django.views.generic import TemplateView

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'customers',CustomerViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    # social-auth-app-django (github,google,authO)
    # only for authO =  python-jose no need for urls/settings
    path('',include('social_django.urls')),
]
urlpatterns += i18n_patterns(
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('users/', include('users.urls')),
    path('posts/',include('posts.urls')),
)
# (temp) path for browser api view
urlpatterns += [
    path('api-auth/', include('rest_framework.urls'))
]
# djoser path
urlpatterns += [
    path('auth/', include('djoser.urls.authtoken')),
    path('auth/', include('djoser.urls')),
    # jwt auth
    path('auth/', include('djoser.urls.jwt')),
]

# other api paths
urlpatterns +=[
    path('api/v1/', include(router.urls)),
]


# djoser urls
# ************************************
# step N 1: register user

# url: auth/users/
# other features
# url: auth/users/...кучи разных экстра для создания и опереций над юзерами
# smth like: confirm email, reset psw
# step N2
# activate
# auth/users/activate
# http://127.0.0.1:8080/activate/NDM/5ir-d995..


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import (PostFormListView,
                    PostDelete,
                    PostHide,
                    ReportListView,
                    ReportPost,
                    BlockUser,
                    )

app_name = 'posts'

urlpatterns = [
    path('',PostFormListView.as_view(),name="post-form"),
    path('delete-post/<int:pk>/',PostDelete.as_view(),name="post-delete"),
    path('hide-post/<int:pk>/',PostHide.as_view(),name="post-hide"),
    path('reports/',ReportListView.as_view(),name="report-list"),
    path('report-post/<int:pk>/',ReportPost.as_view(),name="report-post"),
    path('block-user/<int:pk>/',BlockUser.as_view(),name="ban-user"),
]

users/urls.py
from django.urls import path
from .views import (CustomerRegister,
                    CustomerDashboard,
                    EmployeeRegister,
                    EmployeeDashboard,
                    logout
                    )

app_name = 'users'

urlpatterns = [
    path('customer-registration/', CustomerRegister.as_view(),name='customer-signup'),
    path('customer-dashboard/', CustomerDashboard.as_view(),name='customer-dashboard'),
    path('employee-registration/', EmployeeRegister.as_view(),name='employee-signup'),
    path('employee-dashboard/', EmployeeDashboard.as_view(),name='employee-dashboard'),
    path('logout/',logout,name='logout')
    
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=255, default="")
    count = models.SmallIntegerField(default=0)
    hidden = models.BooleanField(default=False)
    date_hidden = models.DateTimeField(null=True, blank=True)
    deleted_by = models.ForeignKey(User,
                                   on_delete=models.DO_NOTHING,
                                   blank=True,
                                   null=True,
                                   related_name="moderator")

    def __str__(self):
        return f'Written by {self.user}'

    class Meta:
        permissions = (('can_mark_inappropriate', 'can mark as inappropr'),)


class Report(models.Model):
    reported_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f"done by:{self.reported_by} on post {self.post.id}"

templates/_extra/nav-bar.html
{% load static i18n %} 

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'posts:post-form' %}">All Posts</a>
      </li>
      {% if perms.posts.view_report %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'posts:report-list' %}">Reports</a>
      </li>
      {% endif %}
      <li class="nav-item active">
        <a class="nav-link" href="#">{{user}}</span></a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dashboard
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">{% translate 'Profile' %}</a>
          <a class="dropdown-item" href="#">{% translate 'Update Profile' %}</a>
        </div>
        </li>
      
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:logout' %}">{% translate 'LogOut' %}</a>
      </li>
      
      {% else %}
       <li class="nav-item">
        <a class="nav-link" href="/login/auth0">{% translate 'Auth0-LogIn' %}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">{% translate 'SignUp' %}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">{% translate 'Log In' %}</a>
      </li>
      {% endif %}
    </ul> 
        
      
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>