beurs/urls.py
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from api.account.viewsets import UserViewSet, CustomerViewSet
from django.views.generic import TemplateView

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'customers',CustomerViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    # social-auth-app-django (github,google,authO)
    # only for authO =  python-jose no need for urls/settings
    path('',include('social_django.urls')),
]
urlpatterns += i18n_patterns(
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('users/', include('users.urls')),
    path('posts/',include('posts.urls')),
)
# (temp) path for browser api view
urlpatterns += [
    path('api-auth/', include('rest_framework.urls'))
]
# djoser path
urlpatterns += [
    path('auth/', include('djoser.urls.authtoken')),
    path('auth/', include('djoser.urls')),
    # jwt auth
    path('auth/', include('djoser.urls.jwt')),
]

# other api paths
urlpatterns +=[
    path('api/v1/', include(router.urls)),
]


# djoser urls
# ************************************
# step N 1: register user

# url: auth/users/
# other features
# url: auth/users/...кучи разных экстра для создания и опереций над юзерами
# smth like: confirm email, reset psw
# step N2
# activate
# auth/users/activate
# http://127.0.0.1:8080/activate/NDM/5ir-d995..


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import (CustomerRegister,
                    CustomerDashboard,
                    EmployeeRegister,
                    EmployeeDashboard,
                    logout
                    )

app_name = 'users'

urlpatterns = [
    path('customer-registration/', CustomerRegister.as_view(),name='customer-signup'),
    path('customer-dashboard/', CustomerDashboard.as_view(),name='customer-dashboard'),
    path('employee-registration/', EmployeeRegister.as_view(),name='employee-signup'),
    path('employee-dashboard/', EmployeeDashboard.as_view(),name='employee-dashboard'),
    path('logout/',logout,name='logout')
    
]

templates/base.html
<!DOCTYPE html>
{% load static i18n %} 
<html lang="{{LANGUAGE_CODE}}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% translate 'Home' %}{% endblock %}</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- let op: use here staic/bootstrap folder -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block style %}
    {% endblock %}
</head>
<body>
    {% include '_extra/nav-bar.html' %}
    <div>
        {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
       {% endif %}         
    </div>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
   <!-- Compiled and minified JavaScript -->
   <script  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js">
   </script>
   <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- for cookies -->
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script> 
    <script src="{% static 'js/script.js' %}"></script>
    {% block js %}

    {% endblock %}
    
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static i18n %} 

{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col col-md-10">
            <h1 class="text-center">{% translate 'Welcome to freelance exchange' %}, 
                {% if user.is_authenticated %}{{user}}{% else %}{% translate 'guest' %}{% endif %}
            </h1>
        </div>
    </div>
    <div class="mt-3 d-flex justify-content-between">
        <div >
            <button class="btn btn-success"><a href="{% url 'users:customer-signup' %}">
                {% translate 'Register as a customer' %}</a>
            </button>
        </div>
        <div >
            <button class="btn btn-success"><a href="{% url 'users:employee-signup' %}">{% translate 'Register as an employee' %}</a>
            </button>
        </div>
    </div>    

</div>

{% endblock content %}